# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(617, 499)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.empTable = QtWidgets.QTableWidget(self.centralWidget)
        self.empTable.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.empTable.setAutoFillBackground(False)
        self.empTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.empTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.empTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.empTable.setTabKeyNavigation(False)
        self.empTable.setAlternatingRowColors(True)
        self.empTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.empTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.empTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.empTable.setRowCount(1)
        self.empTable.setColumnCount(5)
        self.empTable.setObjectName("empTable")
        item = QtWidgets.QTableWidgetItem()
        self.empTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.empTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.empTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.empTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.empTable.setHorizontalHeaderItem(4, item)
        self.empTable.horizontalHeader().setCascadingSectionResizes(False)
        self.empTable.horizontalHeader().setMinimumSectionSize(35)
        self.empTable.horizontalHeader().setSortIndicatorShown(True)
        self.empTable.horizontalHeader().setStretchLastSection(True)
        self.empTable.verticalHeader().setCascadingSectionResizes(False)
        self.empTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.empTable, 0, 0, 1, 1)
        self.addButton = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setMaximumSize(QtCore.QSize(147555, 16777215))
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 1, 0, 1, 1)
        self.departmentButton = QtWidgets.QPushButton(self.centralWidget)
        self.departmentButton.setObjectName("departmentButton")
        self.gridLayout.addWidget(self.departmentButton, 4, 0, 1, 1)
        self.searchButton = QtWidgets.QPushButton(self.centralWidget)
        self.searchButton.setObjectName("searchButton")
        self.gridLayout.addWidget(self.searchButton, 5, 0, 1, 1)
        self.exitButton = QtWidgets.QPushButton(self.centralWidget)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 6, 0, 1, 1)
        self.editButton = QtWidgets.QPushButton(self.centralWidget)
        self.editButton.setObjectName("editButton")
        self.gridLayout.addWidget(self.editButton, 2, 0, 1, 1)
        self.deleteButton = QtWidgets.QPushButton(self.centralWidget)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout.addWidget(self.deleteButton, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 617, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "База данных сотрудников"))
        self.empTable.setSortingEnabled(True)
        item = self.empTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.empTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Имя"))
        item = self.empTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Возраст"))
        item = self.empTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Должность"))
        item = self.empTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Отдел"))
        self.addButton.setText(_translate("MainWindow", "Добавить сотрудника"))
        self.departmentButton.setText(_translate("MainWindow", "Редактор отделов"))
        self.searchButton.setText(_translate("MainWindow", "Поиск сотрудников"))
        self.exitButton.setText(_translate("MainWindow", "Выход"))
        self.editButton.setText(_translate("MainWindow", "Редактировать сотрудника"))
        self.deleteButton.setText(_translate("MainWindow", "Удалить сотрудника"))
        self.actionDelete.setText(_translate("MainWindow", "Удалить"))
        self.actionDelete.setToolTip(_translate("MainWindow", "Delete record"))
        self.actionEdit.setText(_translate("MainWindow", "Изменить"))

